//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4971
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManage.FileMgtService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnValueInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceManage.FileMgtService.Pro_File))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceManage.FileMgtService.ArrayOfGuid))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceManage.FileMgtService.Pro_File[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceManage.FileMgtService.ArrayOfString))]
    public partial class ReturnValueInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool boolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageTextField;
        
        private bool isErrorField;
        
        private int RecordIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool boolValue {
            get {
                return this.boolValueField;
            }
            set {
                if ((this.boolValueField.Equals(value) != true)) {
                    this.boolValueField = value;
                    this.RaisePropertyChanged("boolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public object ValueObject {
            get {
                return this.ValueObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueObjectField, value) != true)) {
                    this.ValueObjectField = value;
                    this.RaisePropertyChanged("ValueObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageText {
            get {
                return this.messageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.messageTextField, value) != true)) {
                    this.messageTextField = value;
                    this.RaisePropertyChanged("messageText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool isError {
            get {
                return this.isErrorField;
            }
            set {
                if ((this.isErrorField.Equals(value) != true)) {
                    this.isErrorField = value;
                    this.RaisePropertyChanged("isError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int RecordID {
            get {
                return this.RecordIDField;
            }
            set {
                if ((this.RecordIDField.Equals(value) != true)) {
                    this.RecordIDField = value;
                    this.RaisePropertyChanged("RecordID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pro_File", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Pro_File : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid pfl_RecordIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cSuffixField;
        
        private double pfl_fFilesizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cRelativePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cAbsolutePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cAddField;
        
        private System.DateTime pfl_dAddDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cLastField;
        
        private System.DateTime pfl_cLastDateField;
        
        private int pfl_RecordID_LengthField;
        
        private int pfl_cProject_LengthField;
        
        private int pfl_cItem_LengthField;
        
        private int pfl_cFileName_LengthField;
        
        private int pfl_cSuffix_LengthField;
        
        private int pfl_fFilesize_LengthField;
        
        private int pfl_cRelativePath_LengthField;
        
        private int pfl_cAbsolutePath_LengthField;
        
        private int pfl_cAdd_LengthField;
        
        private int pfl_dAddDate_LengthField;
        
        private int pf_cLast_LengthField;
        
        private int pf_cLastDate_LengthField;
        
        private int RecordIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid pfl_RecordID {
            get {
                return this.pfl_RecordIDField;
            }
            set {
                if ((this.pfl_RecordIDField.Equals(value) != true)) {
                    this.pfl_RecordIDField = value;
                    this.RaisePropertyChanged("pfl_RecordID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string pfl_cProject {
            get {
                return this.pfl_cProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cProjectField, value) != true)) {
                    this.pfl_cProjectField = value;
                    this.RaisePropertyChanged("pfl_cProject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pfl_cItem {
            get {
                return this.pfl_cItemField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cItemField, value) != true)) {
                    this.pfl_cItemField = value;
                    this.RaisePropertyChanged("pfl_cItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pfl_cFileName {
            get {
                return this.pfl_cFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cFileNameField, value) != true)) {
                    this.pfl_cFileNameField = value;
                    this.RaisePropertyChanged("pfl_cFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pfl_cSuffix {
            get {
                return this.pfl_cSuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cSuffixField, value) != true)) {
                    this.pfl_cSuffixField = value;
                    this.RaisePropertyChanged("pfl_cSuffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double pfl_fFilesize {
            get {
                return this.pfl_fFilesizeField;
            }
            set {
                if ((this.pfl_fFilesizeField.Equals(value) != true)) {
                    this.pfl_fFilesizeField = value;
                    this.RaisePropertyChanged("pfl_fFilesize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pfl_cRelativePath {
            get {
                return this.pfl_cRelativePathField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cRelativePathField, value) != true)) {
                    this.pfl_cRelativePathField = value;
                    this.RaisePropertyChanged("pfl_cRelativePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string pfl_cAbsolutePath {
            get {
                return this.pfl_cAbsolutePathField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cAbsolutePathField, value) != true)) {
                    this.pfl_cAbsolutePathField = value;
                    this.RaisePropertyChanged("pfl_cAbsolutePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string pfl_cAdd {
            get {
                return this.pfl_cAddField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cAddField, value) != true)) {
                    this.pfl_cAddField = value;
                    this.RaisePropertyChanged("pfl_cAdd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime pfl_dAddDate {
            get {
                return this.pfl_dAddDateField;
            }
            set {
                if ((this.pfl_dAddDateField.Equals(value) != true)) {
                    this.pfl_dAddDateField = value;
                    this.RaisePropertyChanged("pfl_dAddDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string pfl_cLast {
            get {
                return this.pfl_cLastField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cLastField, value) != true)) {
                    this.pfl_cLastField = value;
                    this.RaisePropertyChanged("pfl_cLast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime pfl_cLastDate {
            get {
                return this.pfl_cLastDateField;
            }
            set {
                if ((this.pfl_cLastDateField.Equals(value) != true)) {
                    this.pfl_cLastDateField = value;
                    this.RaisePropertyChanged("pfl_cLastDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int pfl_RecordID_Length {
            get {
                return this.pfl_RecordID_LengthField;
            }
            set {
                if ((this.pfl_RecordID_LengthField.Equals(value) != true)) {
                    this.pfl_RecordID_LengthField = value;
                    this.RaisePropertyChanged("pfl_RecordID_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int pfl_cProject_Length {
            get {
                return this.pfl_cProject_LengthField;
            }
            set {
                if ((this.pfl_cProject_LengthField.Equals(value) != true)) {
                    this.pfl_cProject_LengthField = value;
                    this.RaisePropertyChanged("pfl_cProject_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public int pfl_cItem_Length {
            get {
                return this.pfl_cItem_LengthField;
            }
            set {
                if ((this.pfl_cItem_LengthField.Equals(value) != true)) {
                    this.pfl_cItem_LengthField = value;
                    this.RaisePropertyChanged("pfl_cItem_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public int pfl_cFileName_Length {
            get {
                return this.pfl_cFileName_LengthField;
            }
            set {
                if ((this.pfl_cFileName_LengthField.Equals(value) != true)) {
                    this.pfl_cFileName_LengthField = value;
                    this.RaisePropertyChanged("pfl_cFileName_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public int pfl_cSuffix_Length {
            get {
                return this.pfl_cSuffix_LengthField;
            }
            set {
                if ((this.pfl_cSuffix_LengthField.Equals(value) != true)) {
                    this.pfl_cSuffix_LengthField = value;
                    this.RaisePropertyChanged("pfl_cSuffix_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int pfl_fFilesize_Length {
            get {
                return this.pfl_fFilesize_LengthField;
            }
            set {
                if ((this.pfl_fFilesize_LengthField.Equals(value) != true)) {
                    this.pfl_fFilesize_LengthField = value;
                    this.RaisePropertyChanged("pfl_fFilesize_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int pfl_cRelativePath_Length {
            get {
                return this.pfl_cRelativePath_LengthField;
            }
            set {
                if ((this.pfl_cRelativePath_LengthField.Equals(value) != true)) {
                    this.pfl_cRelativePath_LengthField = value;
                    this.RaisePropertyChanged("pfl_cRelativePath_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int pfl_cAbsolutePath_Length {
            get {
                return this.pfl_cAbsolutePath_LengthField;
            }
            set {
                if ((this.pfl_cAbsolutePath_LengthField.Equals(value) != true)) {
                    this.pfl_cAbsolutePath_LengthField = value;
                    this.RaisePropertyChanged("pfl_cAbsolutePath_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int pfl_cAdd_Length {
            get {
                return this.pfl_cAdd_LengthField;
            }
            set {
                if ((this.pfl_cAdd_LengthField.Equals(value) != true)) {
                    this.pfl_cAdd_LengthField = value;
                    this.RaisePropertyChanged("pfl_cAdd_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public int pfl_dAddDate_Length {
            get {
                return this.pfl_dAddDate_LengthField;
            }
            set {
                if ((this.pfl_dAddDate_LengthField.Equals(value) != true)) {
                    this.pfl_dAddDate_LengthField = value;
                    this.RaisePropertyChanged("pfl_dAddDate_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int pf_cLast_Length {
            get {
                return this.pf_cLast_LengthField;
            }
            set {
                if ((this.pf_cLast_LengthField.Equals(value) != true)) {
                    this.pf_cLast_LengthField = value;
                    this.RaisePropertyChanged("pf_cLast_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public int pf_cLastDate_Length {
            get {
                return this.pf_cLastDate_LengthField;
            }
            set {
                if ((this.pf_cLastDate_LengthField.Equals(value) != true)) {
                    this.pf_cLastDate_LengthField = value;
                    this.RaisePropertyChanged("pf_cLastDate_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public int RecordID {
            get {
                return this.RecordIDField;
            }
            set {
                if ((this.RecordIDField.Equals(value) != true)) {
                    this.RecordIDField = value;
                    this.RaisePropertyChanged("RecordID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfGuid", Namespace="http://tempuri.org/", ItemName="guid")]
    [System.SerializableAttribute()]
    public class ArrayOfGuid : System.Collections.Generic.List<System.Guid> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileMgtService.FileMgtSoap")]
    public interface FileMgtSoap {
        
        // CODEGEN: Generating message contract since element name project from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveBytes", ReplyAction="*")]
        ServiceManage.FileMgtService.SaveBytesResponse SaveBytes(ServiceManage.FileMgtService.SaveBytesRequest request);
        
        // CODEGEN: Generating message contract since element name project from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        ServiceManage.FileMgtService.SaveResponse Save(ServiceManage.FileMgtService.SaveRequest request);
        
        // CODEGEN: Generating message contract since element name project from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveHttpFile", ReplyAction="*")]
        ServiceManage.FileMgtService.SaveHttpFileResponse SaveHttpFile(ServiceManage.FileMgtService.SaveHttpFileRequest request);
        
        // CODEGEN: Generating message contract since element name project from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBytes", ReplyAction="*")]
        ServiceManage.FileMgtService.UpdateBytesResponse UpdateBytes(ServiceManage.FileMgtService.UpdateBytesRequest request);
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateById", ReplyAction="*")]
        ServiceManage.FileMgtService.UpdateByIdResponse UpdateById(ServiceManage.FileMgtService.UpdateByIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetFileRelativePathResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileRelativePath", ReplyAction="*")]
        ServiceManage.FileMgtService.GetFileRelativePathResponse GetFileRelativePath(ServiceManage.FileMgtService.GetFileRelativePathRequest request);
        
        // CODEGEN: Generating message contract since element name GetFileBytesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileBytes", ReplyAction="*")]
        ServiceManage.FileMgtService.GetFileBytesResponse GetFileBytes(ServiceManage.FileMgtService.GetFileBytesRequest request);
        
        // CODEGEN: Generating message contract since element name GetPro_FileResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPro_File", ReplyAction="*")]
        ServiceManage.FileMgtService.GetPro_FileResponse GetPro_File(ServiceManage.FileMgtService.GetPro_FileRequest request);
        
        // CODEGEN: Generating message contract since element name recordIds from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPro_Files", ReplyAction="*")]
        ServiceManage.FileMgtService.GetPro_FilesResponse GetPro_Files(ServiceManage.FileMgtService.GetPro_FilesRequest request);
        
        // CODEGEN: Generating message contract since element name DeletePro_FileResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePro_File", ReplyAction="*")]
        ServiceManage.FileMgtService.DeletePro_FileResponse DeletePro_File(ServiceManage.FileMgtService.DeletePro_FileRequest request);
        
        // CODEGEN: Generating message contract since element name recordIds from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileRelativePaths", ReplyAction="*")]
        ServiceManage.FileMgtService.GetFileRelativePathsResponse GetFileRelativePaths(ServiceManage.FileMgtService.GetFileRelativePathsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveBytes", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.SaveBytesRequestBody Body;
        
        public SaveBytesRequest() {
        }
        
        public SaveBytesRequest(ServiceManage.FileMgtService.SaveBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveBytesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string project;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string item;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] bytes;
        
        public SaveBytesRequestBody() {
        }
        
        public SaveBytesRequestBody(string project, string item, string fileName, byte[] bytes) {
            this.project = project;
            this.item = item;
            this.fileName = fileName;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveBytesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.SaveBytesResponseBody Body;
        
        public SaveBytesResponse() {
        }
        
        public SaveBytesResponse(ServiceManage.FileMgtService.SaveBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceManage.FileMgtService.ReturnValueInfo SaveBytesResult;
        
        public SaveBytesResponseBody() {
        }
        
        public SaveBytesResponseBody(ServiceManage.FileMgtService.ReturnValueInfo SaveBytesResult) {
            this.SaveBytesResult = SaveBytesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Save", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.SaveRequestBody Body;
        
        public SaveRequest() {
        }
        
        public SaveRequest(ServiceManage.FileMgtService.SaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string project;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string item;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string filePath;
        
        public SaveRequestBody() {
        }
        
        public SaveRequestBody(string project, string item, string filePath) {
            this.project = project;
            this.item = item;
            this.filePath = filePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.SaveResponseBody Body;
        
        public SaveResponse() {
        }
        
        public SaveResponse(ServiceManage.FileMgtService.SaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceManage.FileMgtService.ReturnValueInfo SaveResult;
        
        public SaveResponseBody() {
        }
        
        public SaveResponseBody(ServiceManage.FileMgtService.ReturnValueInfo SaveResult) {
            this.SaveResult = SaveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveHttpFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveHttpFile", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.SaveHttpFileRequestBody Body;
        
        public SaveHttpFileRequest() {
        }
        
        public SaveHttpFileRequest(ServiceManage.FileMgtService.SaveHttpFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveHttpFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string project;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string item;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string uri;
        
        public SaveHttpFileRequestBody() {
        }
        
        public SaveHttpFileRequestBody(string project, string item, string uri) {
            this.project = project;
            this.item = item;
            this.uri = uri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveHttpFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveHttpFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.SaveHttpFileResponseBody Body;
        
        public SaveHttpFileResponse() {
        }
        
        public SaveHttpFileResponse(ServiceManage.FileMgtService.SaveHttpFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveHttpFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceManage.FileMgtService.ReturnValueInfo SaveHttpFileResult;
        
        public SaveHttpFileResponseBody() {
        }
        
        public SaveHttpFileResponseBody(ServiceManage.FileMgtService.ReturnValueInfo SaveHttpFileResult) {
            this.SaveHttpFileResult = SaveHttpFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBytes", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.UpdateBytesRequestBody Body;
        
        public UpdateBytesRequest() {
        }
        
        public UpdateBytesRequest(ServiceManage.FileMgtService.UpdateBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBytesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid recordId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string project;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string item;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] bytes;
        
        public UpdateBytesRequestBody() {
        }
        
        public UpdateBytesRequestBody(System.Guid recordId, string project, string item, string fileName, byte[] bytes) {
            this.recordId = recordId;
            this.project = project;
            this.item = item;
            this.fileName = fileName;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBytesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.UpdateBytesResponseBody Body;
        
        public UpdateBytesResponse() {
        }
        
        public UpdateBytesResponse(ServiceManage.FileMgtService.UpdateBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceManage.FileMgtService.ReturnValueInfo UpdateBytesResult;
        
        public UpdateBytesResponseBody() {
        }
        
        public UpdateBytesResponseBody(ServiceManage.FileMgtService.ReturnValueInfo UpdateBytesResult) {
            this.UpdateBytesResult = UpdateBytesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateById", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.UpdateByIdRequestBody Body;
        
        public UpdateByIdRequest() {
        }
        
        public UpdateByIdRequest(ServiceManage.FileMgtService.UpdateByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid recordId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] bytes;
        
        public UpdateByIdRequestBody() {
        }
        
        public UpdateByIdRequestBody(System.Guid recordId, string fileName, byte[] bytes) {
            this.recordId = recordId;
            this.fileName = fileName;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.UpdateByIdResponseBody Body;
        
        public UpdateByIdResponse() {
        }
        
        public UpdateByIdResponse(ServiceManage.FileMgtService.UpdateByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceManage.FileMgtService.ReturnValueInfo UpdateByIdResult;
        
        public UpdateByIdResponseBody() {
        }
        
        public UpdateByIdResponseBody(ServiceManage.FileMgtService.ReturnValueInfo UpdateByIdResult) {
            this.UpdateByIdResult = UpdateByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRelativePathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileRelativePath", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.GetFileRelativePathRequestBody Body;
        
        public GetFileRelativePathRequest() {
        }
        
        public GetFileRelativePathRequest(ServiceManage.FileMgtService.GetFileRelativePathRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileRelativePathRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid recordId;
        
        public GetFileRelativePathRequestBody() {
        }
        
        public GetFileRelativePathRequestBody(System.Guid recordId) {
            this.recordId = recordId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRelativePathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileRelativePathResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.GetFileRelativePathResponseBody Body;
        
        public GetFileRelativePathResponse() {
        }
        
        public GetFileRelativePathResponse(ServiceManage.FileMgtService.GetFileRelativePathResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileRelativePathResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFileRelativePathResult;
        
        public GetFileRelativePathResponseBody() {
        }
        
        public GetFileRelativePathResponseBody(string GetFileRelativePathResult) {
            this.GetFileRelativePathResult = GetFileRelativePathResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileBytes", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.GetFileBytesRequestBody Body;
        
        public GetFileBytesRequest() {
        }
        
        public GetFileBytesRequest(ServiceManage.FileMgtService.GetFileBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileBytesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid recordId;
        
        public GetFileBytesRequestBody() {
        }
        
        public GetFileBytesRequestBody(System.Guid recordId) {
            this.recordId = recordId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileBytesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.GetFileBytesResponseBody Body;
        
        public GetFileBytesResponse() {
        }
        
        public GetFileBytesResponse(ServiceManage.FileMgtService.GetFileBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileBytesResult;
        
        public GetFileBytesResponseBody() {
        }
        
        public GetFileBytesResponseBody(byte[] GetFileBytesResult) {
            this.GetFileBytesResult = GetFileBytesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPro_FileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPro_File", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.GetPro_FileRequestBody Body;
        
        public GetPro_FileRequest() {
        }
        
        public GetPro_FileRequest(ServiceManage.FileMgtService.GetPro_FileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPro_FileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid recordId;
        
        public GetPro_FileRequestBody() {
        }
        
        public GetPro_FileRequestBody(System.Guid recordId) {
            this.recordId = recordId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPro_FileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPro_FileResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.GetPro_FileResponseBody Body;
        
        public GetPro_FileResponse() {
        }
        
        public GetPro_FileResponse(ServiceManage.FileMgtService.GetPro_FileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPro_FileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceManage.FileMgtService.Pro_File GetPro_FileResult;
        
        public GetPro_FileResponseBody() {
        }
        
        public GetPro_FileResponseBody(ServiceManage.FileMgtService.Pro_File GetPro_FileResult) {
            this.GetPro_FileResult = GetPro_FileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPro_FilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPro_Files", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.GetPro_FilesRequestBody Body;
        
        public GetPro_FilesRequest() {
        }
        
        public GetPro_FilesRequest(ServiceManage.FileMgtService.GetPro_FilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPro_FilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceManage.FileMgtService.ArrayOfGuid recordIds;
        
        public GetPro_FilesRequestBody() {
        }
        
        public GetPro_FilesRequestBody(ServiceManage.FileMgtService.ArrayOfGuid recordIds) {
            this.recordIds = recordIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPro_FilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPro_FilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.GetPro_FilesResponseBody Body;
        
        public GetPro_FilesResponse() {
        }
        
        public GetPro_FilesResponse(ServiceManage.FileMgtService.GetPro_FilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPro_FilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceManage.FileMgtService.Pro_File[] GetPro_FilesResult;
        
        public GetPro_FilesResponseBody() {
        }
        
        public GetPro_FilesResponseBody(ServiceManage.FileMgtService.Pro_File[] GetPro_FilesResult) {
            this.GetPro_FilesResult = GetPro_FilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePro_FileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePro_File", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.DeletePro_FileRequestBody Body;
        
        public DeletePro_FileRequest() {
        }
        
        public DeletePro_FileRequest(ServiceManage.FileMgtService.DeletePro_FileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletePro_FileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid recordId;
        
        public DeletePro_FileRequestBody() {
        }
        
        public DeletePro_FileRequestBody(System.Guid recordId) {
            this.recordId = recordId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePro_FileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePro_FileResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.DeletePro_FileResponseBody Body;
        
        public DeletePro_FileResponse() {
        }
        
        public DeletePro_FileResponse(ServiceManage.FileMgtService.DeletePro_FileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletePro_FileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceManage.FileMgtService.ReturnValueInfo DeletePro_FileResult;
        
        public DeletePro_FileResponseBody() {
        }
        
        public DeletePro_FileResponseBody(ServiceManage.FileMgtService.ReturnValueInfo DeletePro_FileResult) {
            this.DeletePro_FileResult = DeletePro_FileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRelativePathsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileRelativePaths", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.GetFileRelativePathsRequestBody Body;
        
        public GetFileRelativePathsRequest() {
        }
        
        public GetFileRelativePathsRequest(ServiceManage.FileMgtService.GetFileRelativePathsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileRelativePathsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceManage.FileMgtService.ArrayOfGuid recordIds;
        
        public GetFileRelativePathsRequestBody() {
        }
        
        public GetFileRelativePathsRequestBody(ServiceManage.FileMgtService.ArrayOfGuid recordIds) {
            this.recordIds = recordIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRelativePathsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileRelativePathsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceManage.FileMgtService.GetFileRelativePathsResponseBody Body;
        
        public GetFileRelativePathsResponse() {
        }
        
        public GetFileRelativePathsResponse(ServiceManage.FileMgtService.GetFileRelativePathsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileRelativePathsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceManage.FileMgtService.ArrayOfString GetFileRelativePathsResult;
        
        public GetFileRelativePathsResponseBody() {
        }
        
        public GetFileRelativePathsResponseBody(ServiceManage.FileMgtService.ArrayOfString GetFileRelativePathsResult) {
            this.GetFileRelativePathsResult = GetFileRelativePathsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface FileMgtSoapChannel : ServiceManage.FileMgtService.FileMgtSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class FileMgtSoapClient : System.ServiceModel.ClientBase<ServiceManage.FileMgtService.FileMgtSoap>, ServiceManage.FileMgtService.FileMgtSoap {
        
        public FileMgtSoapClient() {
        }
        
        public FileMgtSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileMgtSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileMgtSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileMgtSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceManage.FileMgtService.SaveBytesResponse ServiceManage.FileMgtService.FileMgtSoap.SaveBytes(ServiceManage.FileMgtService.SaveBytesRequest request) {
            return base.Channel.SaveBytes(request);
        }
        
        public ServiceManage.FileMgtService.ReturnValueInfo SaveBytes(string project, string item, string fileName, byte[] bytes) {
            ServiceManage.FileMgtService.SaveBytesRequest inValue = new ServiceManage.FileMgtService.SaveBytesRequest();
            inValue.Body = new ServiceManage.FileMgtService.SaveBytesRequestBody();
            inValue.Body.project = project;
            inValue.Body.item = item;
            inValue.Body.fileName = fileName;
            inValue.Body.bytes = bytes;
            ServiceManage.FileMgtService.SaveBytesResponse retVal = ((ServiceManage.FileMgtService.FileMgtSoap)(this)).SaveBytes(inValue);
            return retVal.Body.SaveBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceManage.FileMgtService.SaveResponse ServiceManage.FileMgtService.FileMgtSoap.Save(ServiceManage.FileMgtService.SaveRequest request) {
            return base.Channel.Save(request);
        }
        
        public ServiceManage.FileMgtService.ReturnValueInfo Save(string project, string item, string filePath) {
            ServiceManage.FileMgtService.SaveRequest inValue = new ServiceManage.FileMgtService.SaveRequest();
            inValue.Body = new ServiceManage.FileMgtService.SaveRequestBody();
            inValue.Body.project = project;
            inValue.Body.item = item;
            inValue.Body.filePath = filePath;
            ServiceManage.FileMgtService.SaveResponse retVal = ((ServiceManage.FileMgtService.FileMgtSoap)(this)).Save(inValue);
            return retVal.Body.SaveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceManage.FileMgtService.SaveHttpFileResponse ServiceManage.FileMgtService.FileMgtSoap.SaveHttpFile(ServiceManage.FileMgtService.SaveHttpFileRequest request) {
            return base.Channel.SaveHttpFile(request);
        }
        
        public ServiceManage.FileMgtService.ReturnValueInfo SaveHttpFile(string project, string item, string uri) {
            ServiceManage.FileMgtService.SaveHttpFileRequest inValue = new ServiceManage.FileMgtService.SaveHttpFileRequest();
            inValue.Body = new ServiceManage.FileMgtService.SaveHttpFileRequestBody();
            inValue.Body.project = project;
            inValue.Body.item = item;
            inValue.Body.uri = uri;
            ServiceManage.FileMgtService.SaveHttpFileResponse retVal = ((ServiceManage.FileMgtService.FileMgtSoap)(this)).SaveHttpFile(inValue);
            return retVal.Body.SaveHttpFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceManage.FileMgtService.UpdateBytesResponse ServiceManage.FileMgtService.FileMgtSoap.UpdateBytes(ServiceManage.FileMgtService.UpdateBytesRequest request) {
            return base.Channel.UpdateBytes(request);
        }
        
        public ServiceManage.FileMgtService.ReturnValueInfo UpdateBytes(System.Guid recordId, string project, string item, string fileName, byte[] bytes) {
            ServiceManage.FileMgtService.UpdateBytesRequest inValue = new ServiceManage.FileMgtService.UpdateBytesRequest();
            inValue.Body = new ServiceManage.FileMgtService.UpdateBytesRequestBody();
            inValue.Body.recordId = recordId;
            inValue.Body.project = project;
            inValue.Body.item = item;
            inValue.Body.fileName = fileName;
            inValue.Body.bytes = bytes;
            ServiceManage.FileMgtService.UpdateBytesResponse retVal = ((ServiceManage.FileMgtService.FileMgtSoap)(this)).UpdateBytes(inValue);
            return retVal.Body.UpdateBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceManage.FileMgtService.UpdateByIdResponse ServiceManage.FileMgtService.FileMgtSoap.UpdateById(ServiceManage.FileMgtService.UpdateByIdRequest request) {
            return base.Channel.UpdateById(request);
        }
        
        public ServiceManage.FileMgtService.ReturnValueInfo UpdateById(System.Guid recordId, string fileName, byte[] bytes) {
            ServiceManage.FileMgtService.UpdateByIdRequest inValue = new ServiceManage.FileMgtService.UpdateByIdRequest();
            inValue.Body = new ServiceManage.FileMgtService.UpdateByIdRequestBody();
            inValue.Body.recordId = recordId;
            inValue.Body.fileName = fileName;
            inValue.Body.bytes = bytes;
            ServiceManage.FileMgtService.UpdateByIdResponse retVal = ((ServiceManage.FileMgtService.FileMgtSoap)(this)).UpdateById(inValue);
            return retVal.Body.UpdateByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceManage.FileMgtService.GetFileRelativePathResponse ServiceManage.FileMgtService.FileMgtSoap.GetFileRelativePath(ServiceManage.FileMgtService.GetFileRelativePathRequest request) {
            return base.Channel.GetFileRelativePath(request);
        }
        
        public string GetFileRelativePath(System.Guid recordId) {
            ServiceManage.FileMgtService.GetFileRelativePathRequest inValue = new ServiceManage.FileMgtService.GetFileRelativePathRequest();
            inValue.Body = new ServiceManage.FileMgtService.GetFileRelativePathRequestBody();
            inValue.Body.recordId = recordId;
            ServiceManage.FileMgtService.GetFileRelativePathResponse retVal = ((ServiceManage.FileMgtService.FileMgtSoap)(this)).GetFileRelativePath(inValue);
            return retVal.Body.GetFileRelativePathResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceManage.FileMgtService.GetFileBytesResponse ServiceManage.FileMgtService.FileMgtSoap.GetFileBytes(ServiceManage.FileMgtService.GetFileBytesRequest request) {
            return base.Channel.GetFileBytes(request);
        }
        
        public byte[] GetFileBytes(System.Guid recordId) {
            ServiceManage.FileMgtService.GetFileBytesRequest inValue = new ServiceManage.FileMgtService.GetFileBytesRequest();
            inValue.Body = new ServiceManage.FileMgtService.GetFileBytesRequestBody();
            inValue.Body.recordId = recordId;
            ServiceManage.FileMgtService.GetFileBytesResponse retVal = ((ServiceManage.FileMgtService.FileMgtSoap)(this)).GetFileBytes(inValue);
            return retVal.Body.GetFileBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceManage.FileMgtService.GetPro_FileResponse ServiceManage.FileMgtService.FileMgtSoap.GetPro_File(ServiceManage.FileMgtService.GetPro_FileRequest request) {
            return base.Channel.GetPro_File(request);
        }
        
        public ServiceManage.FileMgtService.Pro_File GetPro_File(System.Guid recordId) {
            ServiceManage.FileMgtService.GetPro_FileRequest inValue = new ServiceManage.FileMgtService.GetPro_FileRequest();
            inValue.Body = new ServiceManage.FileMgtService.GetPro_FileRequestBody();
            inValue.Body.recordId = recordId;
            ServiceManage.FileMgtService.GetPro_FileResponse retVal = ((ServiceManage.FileMgtService.FileMgtSoap)(this)).GetPro_File(inValue);
            return retVal.Body.GetPro_FileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceManage.FileMgtService.GetPro_FilesResponse ServiceManage.FileMgtService.FileMgtSoap.GetPro_Files(ServiceManage.FileMgtService.GetPro_FilesRequest request) {
            return base.Channel.GetPro_Files(request);
        }
        
        public ServiceManage.FileMgtService.Pro_File[] GetPro_Files(ServiceManage.FileMgtService.ArrayOfGuid recordIds) {
            ServiceManage.FileMgtService.GetPro_FilesRequest inValue = new ServiceManage.FileMgtService.GetPro_FilesRequest();
            inValue.Body = new ServiceManage.FileMgtService.GetPro_FilesRequestBody();
            inValue.Body.recordIds = recordIds;
            ServiceManage.FileMgtService.GetPro_FilesResponse retVal = ((ServiceManage.FileMgtService.FileMgtSoap)(this)).GetPro_Files(inValue);
            return retVal.Body.GetPro_FilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceManage.FileMgtService.DeletePro_FileResponse ServiceManage.FileMgtService.FileMgtSoap.DeletePro_File(ServiceManage.FileMgtService.DeletePro_FileRequest request) {
            return base.Channel.DeletePro_File(request);
        }
        
        public ServiceManage.FileMgtService.ReturnValueInfo DeletePro_File(System.Guid recordId) {
            ServiceManage.FileMgtService.DeletePro_FileRequest inValue = new ServiceManage.FileMgtService.DeletePro_FileRequest();
            inValue.Body = new ServiceManage.FileMgtService.DeletePro_FileRequestBody();
            inValue.Body.recordId = recordId;
            ServiceManage.FileMgtService.DeletePro_FileResponse retVal = ((ServiceManage.FileMgtService.FileMgtSoap)(this)).DeletePro_File(inValue);
            return retVal.Body.DeletePro_FileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceManage.FileMgtService.GetFileRelativePathsResponse ServiceManage.FileMgtService.FileMgtSoap.GetFileRelativePaths(ServiceManage.FileMgtService.GetFileRelativePathsRequest request) {
            return base.Channel.GetFileRelativePaths(request);
        }
        
        public ServiceManage.FileMgtService.ArrayOfString GetFileRelativePaths(ServiceManage.FileMgtService.ArrayOfGuid recordIds) {
            ServiceManage.FileMgtService.GetFileRelativePathsRequest inValue = new ServiceManage.FileMgtService.GetFileRelativePathsRequest();
            inValue.Body = new ServiceManage.FileMgtService.GetFileRelativePathsRequestBody();
            inValue.Body.recordIds = recordIds;
            ServiceManage.FileMgtService.GetFileRelativePathsResponse retVal = ((ServiceManage.FileMgtService.FileMgtSoap)(this)).GetFileRelativePaths(inValue);
            return retVal.Body.GetFileRelativePathsResult;
        }
    }
}
