//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.FileMgtService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnValueInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Common.FileMgtService.Pro_File))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Common.FileMgtService.ArrayOfGuid))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Common.FileMgtService.Pro_File[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Common.FileMgtService.ArrayOfString))]
    public partial class ReturnValueInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool boolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageTextField;
        
        private bool isErrorField;
        
        private int RecordIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool boolValue {
            get {
                return this.boolValueField;
            }
            set {
                if ((this.boolValueField.Equals(value) != true)) {
                    this.boolValueField = value;
                    this.RaisePropertyChanged("boolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public object ValueObject {
            get {
                return this.ValueObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueObjectField, value) != true)) {
                    this.ValueObjectField = value;
                    this.RaisePropertyChanged("ValueObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageText {
            get {
                return this.messageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.messageTextField, value) != true)) {
                    this.messageTextField = value;
                    this.RaisePropertyChanged("messageText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool isError {
            get {
                return this.isErrorField;
            }
            set {
                if ((this.isErrorField.Equals(value) != true)) {
                    this.isErrorField = value;
                    this.RaisePropertyChanged("isError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int RecordID {
            get {
                return this.RecordIDField;
            }
            set {
                if ((this.RecordIDField.Equals(value) != true)) {
                    this.RecordIDField = value;
                    this.RaisePropertyChanged("RecordID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pro_File", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Pro_File : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid pfl_RecordIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cSuffixField;
        
        private double pfl_fFilesizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cRelativePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cAbsolutePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cAddField;
        
        private System.DateTime pfl_dAddDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pfl_cLastField;
        
        private System.DateTime pfl_cLastDateField;
        
        private int pfl_RecordID_LengthField;
        
        private int pfl_cProject_LengthField;
        
        private int pfl_cItem_LengthField;
        
        private int pfl_cFileName_LengthField;
        
        private int pfl_cSuffix_LengthField;
        
        private int pfl_fFilesize_LengthField;
        
        private int pfl_cRelativePath_LengthField;
        
        private int pfl_cAbsolutePath_LengthField;
        
        private int pfl_cAdd_LengthField;
        
        private int pfl_dAddDate_LengthField;
        
        private int pf_cLast_LengthField;
        
        private int pf_cLastDate_LengthField;
        
        private int RecordIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid pfl_RecordID {
            get {
                return this.pfl_RecordIDField;
            }
            set {
                if ((this.pfl_RecordIDField.Equals(value) != true)) {
                    this.pfl_RecordIDField = value;
                    this.RaisePropertyChanged("pfl_RecordID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string pfl_cProject {
            get {
                return this.pfl_cProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cProjectField, value) != true)) {
                    this.pfl_cProjectField = value;
                    this.RaisePropertyChanged("pfl_cProject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pfl_cItem {
            get {
                return this.pfl_cItemField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cItemField, value) != true)) {
                    this.pfl_cItemField = value;
                    this.RaisePropertyChanged("pfl_cItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pfl_cFileName {
            get {
                return this.pfl_cFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cFileNameField, value) != true)) {
                    this.pfl_cFileNameField = value;
                    this.RaisePropertyChanged("pfl_cFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pfl_cSuffix {
            get {
                return this.pfl_cSuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cSuffixField, value) != true)) {
                    this.pfl_cSuffixField = value;
                    this.RaisePropertyChanged("pfl_cSuffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double pfl_fFilesize {
            get {
                return this.pfl_fFilesizeField;
            }
            set {
                if ((this.pfl_fFilesizeField.Equals(value) != true)) {
                    this.pfl_fFilesizeField = value;
                    this.RaisePropertyChanged("pfl_fFilesize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pfl_cRelativePath {
            get {
                return this.pfl_cRelativePathField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cRelativePathField, value) != true)) {
                    this.pfl_cRelativePathField = value;
                    this.RaisePropertyChanged("pfl_cRelativePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string pfl_cAbsolutePath {
            get {
                return this.pfl_cAbsolutePathField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cAbsolutePathField, value) != true)) {
                    this.pfl_cAbsolutePathField = value;
                    this.RaisePropertyChanged("pfl_cAbsolutePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string pfl_cAdd {
            get {
                return this.pfl_cAddField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cAddField, value) != true)) {
                    this.pfl_cAddField = value;
                    this.RaisePropertyChanged("pfl_cAdd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime pfl_dAddDate {
            get {
                return this.pfl_dAddDateField;
            }
            set {
                if ((this.pfl_dAddDateField.Equals(value) != true)) {
                    this.pfl_dAddDateField = value;
                    this.RaisePropertyChanged("pfl_dAddDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string pfl_cLast {
            get {
                return this.pfl_cLastField;
            }
            set {
                if ((object.ReferenceEquals(this.pfl_cLastField, value) != true)) {
                    this.pfl_cLastField = value;
                    this.RaisePropertyChanged("pfl_cLast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime pfl_cLastDate {
            get {
                return this.pfl_cLastDateField;
            }
            set {
                if ((this.pfl_cLastDateField.Equals(value) != true)) {
                    this.pfl_cLastDateField = value;
                    this.RaisePropertyChanged("pfl_cLastDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int pfl_RecordID_Length {
            get {
                return this.pfl_RecordID_LengthField;
            }
            set {
                if ((this.pfl_RecordID_LengthField.Equals(value) != true)) {
                    this.pfl_RecordID_LengthField = value;
                    this.RaisePropertyChanged("pfl_RecordID_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int pfl_cProject_Length {
            get {
                return this.pfl_cProject_LengthField;
            }
            set {
                if ((this.pfl_cProject_LengthField.Equals(value) != true)) {
                    this.pfl_cProject_LengthField = value;
                    this.RaisePropertyChanged("pfl_cProject_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public int pfl_cItem_Length {
            get {
                return this.pfl_cItem_LengthField;
            }
            set {
                if ((this.pfl_cItem_LengthField.Equals(value) != true)) {
                    this.pfl_cItem_LengthField = value;
                    this.RaisePropertyChanged("pfl_cItem_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public int pfl_cFileName_Length {
            get {
                return this.pfl_cFileName_LengthField;
            }
            set {
                if ((this.pfl_cFileName_LengthField.Equals(value) != true)) {
                    this.pfl_cFileName_LengthField = value;
                    this.RaisePropertyChanged("pfl_cFileName_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public int pfl_cSuffix_Length {
            get {
                return this.pfl_cSuffix_LengthField;
            }
            set {
                if ((this.pfl_cSuffix_LengthField.Equals(value) != true)) {
                    this.pfl_cSuffix_LengthField = value;
                    this.RaisePropertyChanged("pfl_cSuffix_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public int pfl_fFilesize_Length {
            get {
                return this.pfl_fFilesize_LengthField;
            }
            set {
                if ((this.pfl_fFilesize_LengthField.Equals(value) != true)) {
                    this.pfl_fFilesize_LengthField = value;
                    this.RaisePropertyChanged("pfl_fFilesize_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int pfl_cRelativePath_Length {
            get {
                return this.pfl_cRelativePath_LengthField;
            }
            set {
                if ((this.pfl_cRelativePath_LengthField.Equals(value) != true)) {
                    this.pfl_cRelativePath_LengthField = value;
                    this.RaisePropertyChanged("pfl_cRelativePath_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int pfl_cAbsolutePath_Length {
            get {
                return this.pfl_cAbsolutePath_LengthField;
            }
            set {
                if ((this.pfl_cAbsolutePath_LengthField.Equals(value) != true)) {
                    this.pfl_cAbsolutePath_LengthField = value;
                    this.RaisePropertyChanged("pfl_cAbsolutePath_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int pfl_cAdd_Length {
            get {
                return this.pfl_cAdd_LengthField;
            }
            set {
                if ((this.pfl_cAdd_LengthField.Equals(value) != true)) {
                    this.pfl_cAdd_LengthField = value;
                    this.RaisePropertyChanged("pfl_cAdd_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public int pfl_dAddDate_Length {
            get {
                return this.pfl_dAddDate_LengthField;
            }
            set {
                if ((this.pfl_dAddDate_LengthField.Equals(value) != true)) {
                    this.pfl_dAddDate_LengthField = value;
                    this.RaisePropertyChanged("pfl_dAddDate_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int pf_cLast_Length {
            get {
                return this.pf_cLast_LengthField;
            }
            set {
                if ((this.pf_cLast_LengthField.Equals(value) != true)) {
                    this.pf_cLast_LengthField = value;
                    this.RaisePropertyChanged("pf_cLast_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public int pf_cLastDate_Length {
            get {
                return this.pf_cLastDate_LengthField;
            }
            set {
                if ((this.pf_cLastDate_LengthField.Equals(value) != true)) {
                    this.pf_cLastDate_LengthField = value;
                    this.RaisePropertyChanged("pf_cLastDate_Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public int RecordID {
            get {
                return this.RecordIDField;
            }
            set {
                if ((this.RecordIDField.Equals(value) != true)) {
                    this.RecordIDField = value;
                    this.RaisePropertyChanged("RecordID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfGuid", Namespace="http://tempuri.org/", ItemName="guid")]
    [System.SerializableAttribute()]
    public class ArrayOfGuid : System.Collections.Generic.List<System.Guid> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileMgtService.FileMgtSoap")]
    public interface FileMgtSoap {
        
        // CODEGEN: Generating message contract since element name project from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveBytes", ReplyAction="*")]
        Common.FileMgtService.SaveBytesResponse SaveBytes(Common.FileMgtService.SaveBytesRequest request);
        
        // CODEGEN: Generating message contract since element name project from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBytes", ReplyAction="*")]
        Common.FileMgtService.UpdateBytesResponse UpdateBytes(Common.FileMgtService.UpdateBytesRequest request);
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateById", ReplyAction="*")]
        Common.FileMgtService.UpdateByIdResponse UpdateById(Common.FileMgtService.UpdateByIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetFileRelativePathResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileRelativePath", ReplyAction="*")]
        Common.FileMgtService.GetFileRelativePathResponse GetFileRelativePath(Common.FileMgtService.GetFileRelativePathRequest request);
        
        // CODEGEN: Generating message contract since element name GetFileBytesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileBytes", ReplyAction="*")]
        Common.FileMgtService.GetFileBytesResponse GetFileBytes(Common.FileMgtService.GetFileBytesRequest request);
        
        // CODEGEN: Generating message contract since element name GetPro_FileResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPro_File", ReplyAction="*")]
        Common.FileMgtService.GetPro_FileResponse GetPro_File(Common.FileMgtService.GetPro_FileRequest request);
        
        // CODEGEN: Generating message contract since element name recordIds from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPro_Files", ReplyAction="*")]
        Common.FileMgtService.GetPro_FilesResponse GetPro_Files(Common.FileMgtService.GetPro_FilesRequest request);
        
        // CODEGEN: Generating message contract since element name DeletePro_FileResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePro_File", ReplyAction="*")]
        Common.FileMgtService.DeletePro_FileResponse DeletePro_File(Common.FileMgtService.DeletePro_FileRequest request);
        
        // CODEGEN: Generating message contract since element name recordIds from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileRelativePaths", ReplyAction="*")]
        Common.FileMgtService.GetFileRelativePathsResponse GetFileRelativePaths(Common.FileMgtService.GetFileRelativePathsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveBytes", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.SaveBytesRequestBody Body;
        
        public SaveBytesRequest() {
        }
        
        public SaveBytesRequest(Common.FileMgtService.SaveBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveBytesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string project;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string item;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] bytes;
        
        public SaveBytesRequestBody() {
        }
        
        public SaveBytesRequestBody(string project, string item, string fileName, byte[] bytes) {
            this.project = project;
            this.item = item;
            this.fileName = fileName;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveBytesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.SaveBytesResponseBody Body;
        
        public SaveBytesResponse() {
        }
        
        public SaveBytesResponse(Common.FileMgtService.SaveBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Common.FileMgtService.ReturnValueInfo SaveBytesResult;
        
        public SaveBytesResponseBody() {
        }
        
        public SaveBytesResponseBody(Common.FileMgtService.ReturnValueInfo SaveBytesResult) {
            this.SaveBytesResult = SaveBytesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBytes", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.UpdateBytesRequestBody Body;
        
        public UpdateBytesRequest() {
        }
        
        public UpdateBytesRequest(Common.FileMgtService.UpdateBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBytesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid recordId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string project;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string item;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] bytes;
        
        public UpdateBytesRequestBody() {
        }
        
        public UpdateBytesRequestBody(System.Guid recordId, string project, string item, string fileName, byte[] bytes) {
            this.recordId = recordId;
            this.project = project;
            this.item = item;
            this.fileName = fileName;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBytesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.UpdateBytesResponseBody Body;
        
        public UpdateBytesResponse() {
        }
        
        public UpdateBytesResponse(Common.FileMgtService.UpdateBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Common.FileMgtService.ReturnValueInfo UpdateBytesResult;
        
        public UpdateBytesResponseBody() {
        }
        
        public UpdateBytesResponseBody(Common.FileMgtService.ReturnValueInfo UpdateBytesResult) {
            this.UpdateBytesResult = UpdateBytesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateById", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.UpdateByIdRequestBody Body;
        
        public UpdateByIdRequest() {
        }
        
        public UpdateByIdRequest(Common.FileMgtService.UpdateByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid recordId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] bytes;
        
        public UpdateByIdRequestBody() {
        }
        
        public UpdateByIdRequestBody(System.Guid recordId, string fileName, byte[] bytes) {
            this.recordId = recordId;
            this.fileName = fileName;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.UpdateByIdResponseBody Body;
        
        public UpdateByIdResponse() {
        }
        
        public UpdateByIdResponse(Common.FileMgtService.UpdateByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Common.FileMgtService.ReturnValueInfo UpdateByIdResult;
        
        public UpdateByIdResponseBody() {
        }
        
        public UpdateByIdResponseBody(Common.FileMgtService.ReturnValueInfo UpdateByIdResult) {
            this.UpdateByIdResult = UpdateByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRelativePathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileRelativePath", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.GetFileRelativePathRequestBody Body;
        
        public GetFileRelativePathRequest() {
        }
        
        public GetFileRelativePathRequest(Common.FileMgtService.GetFileRelativePathRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileRelativePathRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid recordId;
        
        public GetFileRelativePathRequestBody() {
        }
        
        public GetFileRelativePathRequestBody(System.Guid recordId) {
            this.recordId = recordId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRelativePathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileRelativePathResponse", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.GetFileRelativePathResponseBody Body;
        
        public GetFileRelativePathResponse() {
        }
        
        public GetFileRelativePathResponse(Common.FileMgtService.GetFileRelativePathResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileRelativePathResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFileRelativePathResult;
        
        public GetFileRelativePathResponseBody() {
        }
        
        public GetFileRelativePathResponseBody(string GetFileRelativePathResult) {
            this.GetFileRelativePathResult = GetFileRelativePathResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileBytes", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.GetFileBytesRequestBody Body;
        
        public GetFileBytesRequest() {
        }
        
        public GetFileBytesRequest(Common.FileMgtService.GetFileBytesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileBytesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid recordId;
        
        public GetFileBytesRequestBody() {
        }
        
        public GetFileBytesRequestBody(System.Guid recordId) {
            this.recordId = recordId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileBytesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.GetFileBytesResponseBody Body;
        
        public GetFileBytesResponse() {
        }
        
        public GetFileBytesResponse(Common.FileMgtService.GetFileBytesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileBytesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileBytesResult;
        
        public GetFileBytesResponseBody() {
        }
        
        public GetFileBytesResponseBody(byte[] GetFileBytesResult) {
            this.GetFileBytesResult = GetFileBytesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPro_FileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPro_File", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.GetPro_FileRequestBody Body;
        
        public GetPro_FileRequest() {
        }
        
        public GetPro_FileRequest(Common.FileMgtService.GetPro_FileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPro_FileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid recordId;
        
        public GetPro_FileRequestBody() {
        }
        
        public GetPro_FileRequestBody(System.Guid recordId) {
            this.recordId = recordId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPro_FileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPro_FileResponse", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.GetPro_FileResponseBody Body;
        
        public GetPro_FileResponse() {
        }
        
        public GetPro_FileResponse(Common.FileMgtService.GetPro_FileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPro_FileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Common.FileMgtService.Pro_File GetPro_FileResult;
        
        public GetPro_FileResponseBody() {
        }
        
        public GetPro_FileResponseBody(Common.FileMgtService.Pro_File GetPro_FileResult) {
            this.GetPro_FileResult = GetPro_FileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPro_FilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPro_Files", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.GetPro_FilesRequestBody Body;
        
        public GetPro_FilesRequest() {
        }
        
        public GetPro_FilesRequest(Common.FileMgtService.GetPro_FilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPro_FilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Common.FileMgtService.ArrayOfGuid recordIds;
        
        public GetPro_FilesRequestBody() {
        }
        
        public GetPro_FilesRequestBody(Common.FileMgtService.ArrayOfGuid recordIds) {
            this.recordIds = recordIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPro_FilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPro_FilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.GetPro_FilesResponseBody Body;
        
        public GetPro_FilesResponse() {
        }
        
        public GetPro_FilesResponse(Common.FileMgtService.GetPro_FilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPro_FilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Common.FileMgtService.Pro_File[] GetPro_FilesResult;
        
        public GetPro_FilesResponseBody() {
        }
        
        public GetPro_FilesResponseBody(Common.FileMgtService.Pro_File[] GetPro_FilesResult) {
            this.GetPro_FilesResult = GetPro_FilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePro_FileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePro_File", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.DeletePro_FileRequestBody Body;
        
        public DeletePro_FileRequest() {
        }
        
        public DeletePro_FileRequest(Common.FileMgtService.DeletePro_FileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletePro_FileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid recordId;
        
        public DeletePro_FileRequestBody() {
        }
        
        public DeletePro_FileRequestBody(System.Guid recordId) {
            this.recordId = recordId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletePro_FileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletePro_FileResponse", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.DeletePro_FileResponseBody Body;
        
        public DeletePro_FileResponse() {
        }
        
        public DeletePro_FileResponse(Common.FileMgtService.DeletePro_FileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletePro_FileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Common.FileMgtService.ReturnValueInfo DeletePro_FileResult;
        
        public DeletePro_FileResponseBody() {
        }
        
        public DeletePro_FileResponseBody(Common.FileMgtService.ReturnValueInfo DeletePro_FileResult) {
            this.DeletePro_FileResult = DeletePro_FileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRelativePathsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileRelativePaths", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.GetFileRelativePathsRequestBody Body;
        
        public GetFileRelativePathsRequest() {
        }
        
        public GetFileRelativePathsRequest(Common.FileMgtService.GetFileRelativePathsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileRelativePathsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Common.FileMgtService.ArrayOfGuid recordIds;
        
        public GetFileRelativePathsRequestBody() {
        }
        
        public GetFileRelativePathsRequestBody(Common.FileMgtService.ArrayOfGuid recordIds) {
            this.recordIds = recordIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRelativePathsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileRelativePathsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Common.FileMgtService.GetFileRelativePathsResponseBody Body;
        
        public GetFileRelativePathsResponse() {
        }
        
        public GetFileRelativePathsResponse(Common.FileMgtService.GetFileRelativePathsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileRelativePathsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Common.FileMgtService.ArrayOfString GetFileRelativePathsResult;
        
        public GetFileRelativePathsResponseBody() {
        }
        
        public GetFileRelativePathsResponseBody(Common.FileMgtService.ArrayOfString GetFileRelativePathsResult) {
            this.GetFileRelativePathsResult = GetFileRelativePathsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface FileMgtSoapChannel : Common.FileMgtService.FileMgtSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class FileMgtSoapClient : System.ServiceModel.ClientBase<Common.FileMgtService.FileMgtSoap>, Common.FileMgtService.FileMgtSoap {
        
        public FileMgtSoapClient() {
        }
        
        public FileMgtSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileMgtSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileMgtSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileMgtSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.FileMgtService.SaveBytesResponse Common.FileMgtService.FileMgtSoap.SaveBytes(Common.FileMgtService.SaveBytesRequest request) {
            return base.Channel.SaveBytes(request);
        }
        
        public Common.FileMgtService.ReturnValueInfo SaveBytes(string project, string item, string fileName, byte[] bytes) {
            Common.FileMgtService.SaveBytesRequest inValue = new Common.FileMgtService.SaveBytesRequest();
            inValue.Body = new Common.FileMgtService.SaveBytesRequestBody();
            inValue.Body.project = project;
            inValue.Body.item = item;
            inValue.Body.fileName = fileName;
            inValue.Body.bytes = bytes;
            Common.FileMgtService.SaveBytesResponse retVal = ((Common.FileMgtService.FileMgtSoap)(this)).SaveBytes(inValue);
            return retVal.Body.SaveBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.FileMgtService.UpdateBytesResponse Common.FileMgtService.FileMgtSoap.UpdateBytes(Common.FileMgtService.UpdateBytesRequest request) {
            return base.Channel.UpdateBytes(request);
        }
        
        public Common.FileMgtService.ReturnValueInfo UpdateBytes(System.Guid recordId, string project, string item, string fileName, byte[] bytes) {
            Common.FileMgtService.UpdateBytesRequest inValue = new Common.FileMgtService.UpdateBytesRequest();
            inValue.Body = new Common.FileMgtService.UpdateBytesRequestBody();
            inValue.Body.recordId = recordId;
            inValue.Body.project = project;
            inValue.Body.item = item;
            inValue.Body.fileName = fileName;
            inValue.Body.bytes = bytes;
            Common.FileMgtService.UpdateBytesResponse retVal = ((Common.FileMgtService.FileMgtSoap)(this)).UpdateBytes(inValue);
            return retVal.Body.UpdateBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.FileMgtService.UpdateByIdResponse Common.FileMgtService.FileMgtSoap.UpdateById(Common.FileMgtService.UpdateByIdRequest request) {
            return base.Channel.UpdateById(request);
        }
        
        public Common.FileMgtService.ReturnValueInfo UpdateById(System.Guid recordId, string fileName, byte[] bytes) {
            Common.FileMgtService.UpdateByIdRequest inValue = new Common.FileMgtService.UpdateByIdRequest();
            inValue.Body = new Common.FileMgtService.UpdateByIdRequestBody();
            inValue.Body.recordId = recordId;
            inValue.Body.fileName = fileName;
            inValue.Body.bytes = bytes;
            Common.FileMgtService.UpdateByIdResponse retVal = ((Common.FileMgtService.FileMgtSoap)(this)).UpdateById(inValue);
            return retVal.Body.UpdateByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.FileMgtService.GetFileRelativePathResponse Common.FileMgtService.FileMgtSoap.GetFileRelativePath(Common.FileMgtService.GetFileRelativePathRequest request) {
            return base.Channel.GetFileRelativePath(request);
        }
        
        public string GetFileRelativePath(System.Guid recordId) {
            Common.FileMgtService.GetFileRelativePathRequest inValue = new Common.FileMgtService.GetFileRelativePathRequest();
            inValue.Body = new Common.FileMgtService.GetFileRelativePathRequestBody();
            inValue.Body.recordId = recordId;
            Common.FileMgtService.GetFileRelativePathResponse retVal = ((Common.FileMgtService.FileMgtSoap)(this)).GetFileRelativePath(inValue);
            return retVal.Body.GetFileRelativePathResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.FileMgtService.GetFileBytesResponse Common.FileMgtService.FileMgtSoap.GetFileBytes(Common.FileMgtService.GetFileBytesRequest request) {
            return base.Channel.GetFileBytes(request);
        }
        
        public byte[] GetFileBytes(System.Guid recordId) {
            Common.FileMgtService.GetFileBytesRequest inValue = new Common.FileMgtService.GetFileBytesRequest();
            inValue.Body = new Common.FileMgtService.GetFileBytesRequestBody();
            inValue.Body.recordId = recordId;
            Common.FileMgtService.GetFileBytesResponse retVal = ((Common.FileMgtService.FileMgtSoap)(this)).GetFileBytes(inValue);
            return retVal.Body.GetFileBytesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.FileMgtService.GetPro_FileResponse Common.FileMgtService.FileMgtSoap.GetPro_File(Common.FileMgtService.GetPro_FileRequest request) {
            return base.Channel.GetPro_File(request);
        }
        
        public Common.FileMgtService.Pro_File GetPro_File(System.Guid recordId) {
            Common.FileMgtService.GetPro_FileRequest inValue = new Common.FileMgtService.GetPro_FileRequest();
            inValue.Body = new Common.FileMgtService.GetPro_FileRequestBody();
            inValue.Body.recordId = recordId;
            Common.FileMgtService.GetPro_FileResponse retVal = ((Common.FileMgtService.FileMgtSoap)(this)).GetPro_File(inValue);
            return retVal.Body.GetPro_FileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.FileMgtService.GetPro_FilesResponse Common.FileMgtService.FileMgtSoap.GetPro_Files(Common.FileMgtService.GetPro_FilesRequest request) {
            return base.Channel.GetPro_Files(request);
        }
        
        public Common.FileMgtService.Pro_File[] GetPro_Files(Common.FileMgtService.ArrayOfGuid recordIds) {
            Common.FileMgtService.GetPro_FilesRequest inValue = new Common.FileMgtService.GetPro_FilesRequest();
            inValue.Body = new Common.FileMgtService.GetPro_FilesRequestBody();
            inValue.Body.recordIds = recordIds;
            Common.FileMgtService.GetPro_FilesResponse retVal = ((Common.FileMgtService.FileMgtSoap)(this)).GetPro_Files(inValue);
            return retVal.Body.GetPro_FilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.FileMgtService.DeletePro_FileResponse Common.FileMgtService.FileMgtSoap.DeletePro_File(Common.FileMgtService.DeletePro_FileRequest request) {
            return base.Channel.DeletePro_File(request);
        }
        
        public Common.FileMgtService.ReturnValueInfo DeletePro_File(System.Guid recordId) {
            Common.FileMgtService.DeletePro_FileRequest inValue = new Common.FileMgtService.DeletePro_FileRequest();
            inValue.Body = new Common.FileMgtService.DeletePro_FileRequestBody();
            inValue.Body.recordId = recordId;
            Common.FileMgtService.DeletePro_FileResponse retVal = ((Common.FileMgtService.FileMgtSoap)(this)).DeletePro_File(inValue);
            return retVal.Body.DeletePro_FileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Common.FileMgtService.GetFileRelativePathsResponse Common.FileMgtService.FileMgtSoap.GetFileRelativePaths(Common.FileMgtService.GetFileRelativePathsRequest request) {
            return base.Channel.GetFileRelativePaths(request);
        }
        
        public Common.FileMgtService.ArrayOfString GetFileRelativePaths(Common.FileMgtService.ArrayOfGuid recordIds) {
            Common.FileMgtService.GetFileRelativePathsRequest inValue = new Common.FileMgtService.GetFileRelativePathsRequest();
            inValue.Body = new Common.FileMgtService.GetFileRelativePathsRequestBody();
            inValue.Body.recordIds = recordIds;
            Common.FileMgtService.GetFileRelativePathsResponse retVal = ((Common.FileMgtService.FileMgtSoap)(this)).GetFileRelativePaths(inValue);
            return retVal.Body.GetFileRelativePathsResult;
        }
    }
}
