<?xml version="1.0" encoding="utf-8"?>
<Database Name="VPMSDB" Class="VPMSDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-PAUOG56\SQLEXPRESS;Initial Catalog=VPMSDB;Persist Security Info=True;User ID=dandyyang" SettingsObjectName="LinqToSQLModel.Properties.Settings" SettingsPropertyName="VPMSDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DepartmentMaster_dpm" Member="DepartmentMaster_dpms">
    <Type Name="DepartmentMaster_dpm">
      <Column Name="dpm_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dpm_cNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="dpm_cName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dpm_cRemark" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="dpm_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dpm_dAddDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dpm_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="dpm_dLastDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BuildingMaster_bdm" Member="BuildingMaster_bdms">
    <Type Name="BuildingMaster_bdm">
      <Column Name="bdm_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="bdm_cNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="bdm_cName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="bdm_cRemark" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="bdm_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="bdm_dAddDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="bdm_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="bdm_dLastDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SiteMaster_stm" Member="SiteMaster_stms">
    <Type Name="SiteMaster_stm">
      <Column Name="stm_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="stm_cNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="stm_cBuildingNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="stm_cName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="stm_cRemark" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="stm_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="stm_dAddDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="stm_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="stm_dLastDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SpecialtyMaster_spm" Member="SpecialtyMaster_spms">
    <Type Name="SpecialtyMaster_spm">
      <Column Name="spm_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="spm_cNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="spm_cName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="spm_cDesc" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="spm_cRemark" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="spm_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="spm_dAddDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="spm_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="spm_dLastDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="SpecialtyMaster_spm_SpecialtyMasterCourse_smc" Member="SpecialtyMasterCourse_smcs" ThisKey="spm_iRecordID" OtherKey="smc_iSpecialtyID" Type="SpecialtyMasterCourse_smc" />
    </Type>
  </Table>
  <Table Name="dbo.SpecialtyMasterCourse_smc" Member="SpecialtyMasterCourse_smcs">
    <Type Name="SpecialtyMasterCourse_smc">
      <Column Name="smc_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="smc_iSpecialtyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="smc_cSpecialtyNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="smc_cCourseNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="SpecialtyMaster_spm_SpecialtyMasterCourse_smc" Member="SpecialtyMaster_spm" ThisKey="smc_iSpecialtyID" OtherKey="spm_iRecordID" Type="SpecialtyMaster_spm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CodeMaster_cmt" Member="CodeMaster_cmts">
    <Type Name="CodeMaster_cmt">
      <Column Name="cmt_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cmt_cKey1" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cmt_cKey2" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cmt_cValue" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cmt_fNumber" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="cmt_cRemark" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="cmt_cRemark2" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="cmt_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="cmt_dAddDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="cmt_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="cmt_dLastDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sys_RecordLockRegister_rlr" Member="Sys_RecordLockRegister_rlrs">
    <Type Name="Sys_RecordLockRegister_rlr">
      <Column Name="rlr_cTableName" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rlr_iByLockRecordID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rlr_cKeys" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="rlr_dLockDateTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="rlr_cLockedBy" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Sys_UserMaster_usm" Member="Sys_UserMaster_usms">
    <Type Name="Sys_UserMaster_usm">
      <Column Name="usm_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usm_cUserLoginID" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="usm_cChaName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="usm_cPasswork" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="usm_cEMail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="usm_iLock" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="usm_cRemark" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="usm_cAdd" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="usm_dAddDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="usm_cLast" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="usm_dLastDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Sys_UserMaster_usm_Sys_UserPurview_usp" Member="Sys_UserPurview_usps" ThisKey="usm_cUserLoginID" OtherKey="usp_cUserLoginID" Type="Sys_UserPurview_usp" />
      <Association Name="Sys_UserMaster_usm_Sys_UserRoles_usr" Member="Sys_UserRoles_usrs" ThisKey="usm_cUserLoginID" OtherKey="usr_cUserLoginID" Type="Sys_UserRoles_usr" />
    </Type>
  </Table>
  <Table Name="dbo.Sys_UserPurview_usp" Member="Sys_UserPurview_usps">
    <Type Name="Sys_UserPurview_usp">
      <Column Name="usp_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usp_cUserLoginID" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="usp_cRoleID" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="usp_cPurviewCode" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="usp_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="usp_dAddDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="usp_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="usp_dLastDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Sys_UserMaster_usm_Sys_UserPurview_usp" Member="Sys_UserMaster_usm" ThisKey="usp_cUserLoginID" OtherKey="usm_cUserLoginID" Type="Sys_UserMaster_usm" IsForeignKey="true" />
      <Association Name="Sys_RoleMaster_rlm_Sys_UserPurview_usp" Member="Sys_RoleMaster_rlm" ThisKey="usp_cRoleID" OtherKey="rlm_cRoleID" Type="Sys_RoleMaster_rlm" IsForeignKey="true" />
      <Association Name="Sys_FormPurview_frp_Sys_UserPurview_usp" Member="Sys_FormPurview_frp" ThisKey="usp_cPurviewCode" OtherKey="frp_cPurviewCode" Type="Sys_FormPurview_frp" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sys_RoleMaster_rlm" Member="Sys_RoleMaster_rlms">
    <Type Name="Sys_RoleMaster_rlm">
      <Column Name="rlm_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rlm_cRoleID" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="rlm_cRoleDesc" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="rlm_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="rlm_dAddDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="rlm_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="rlm_dLastDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Sys_RoleMaster_rlm_Sys_UserPurview_usp" Member="Sys_UserPurview_usps" ThisKey="rlm_cRoleID" OtherKey="usp_cRoleID" Type="Sys_UserPurview_usp" />
      <Association Name="Sys_RoleMaster_rlm_Sys_UserRoles_usr" Member="Sys_UserRoles_usrs" ThisKey="rlm_cRoleID" OtherKey="usr_cRoleID" Type="Sys_UserRoles_usr" />
    </Type>
  </Table>
  <Table Name="dbo.Sys_FunctionMaster_fum" Member="Sys_FunctionMaster_fums">
    <Type Name="Sys_FunctionMaster_fum">
      <Column Name="fum_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fum_cFunctionNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="fum_cFunctionDesc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fum_cRemark" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fum_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="fum_dAddDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="fum_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="fum_dLastDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="Sys_FunctionMaster_fum_Sys_FormPurview_frp" Member="Sys_FormPurview_frps" ThisKey="fum_cFunctionNumber" OtherKey="frp_cFunctionNumber" Type="Sys_FormPurview_frp" />
    </Type>
  </Table>
  <Table Name="dbo.Sys_UserRoles_usr" Member="Sys_UserRoles_usrs">
    <Type Name="Sys_UserRoles_usr">
      <Column Name="usr_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usr_cUserLoginID" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="usr_cRoleID" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Sys_UserMaster_usm_Sys_UserRoles_usr" Member="Sys_UserMaster_usm" ThisKey="usr_cUserLoginID" OtherKey="usm_cUserLoginID" Type="Sys_UserMaster_usm" IsForeignKey="true" />
      <Association Name="Sys_RoleMaster_rlm_Sys_UserRoles_usr" Member="Sys_RoleMaster_rlm" ThisKey="usr_cRoleID" OtherKey="rlm_cRoleID" Type="Sys_RoleMaster_rlm" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sys_FormPurview_frp" Member="Sys_FormPurview_frps">
    <Type Name="Sys_FormPurview_frp">
      <Column Name="frp_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="frp_cPurviewCode" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="frp_cFunctionNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="frp_cFormNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Sys_FormPurview_frp_Sys_UserPurview_usp" Member="Sys_UserPurview_usps" ThisKey="frp_cPurviewCode" OtherKey="usp_cPurviewCode" Type="Sys_UserPurview_usp" />
      <Association Name="Sys_FunctionMaster_fum_Sys_FormPurview_frp" Member="Sys_FunctionMaster_fum" ThisKey="frp_cFunctionNumber" OtherKey="fum_cFunctionNumber" Type="Sys_FunctionMaster_fum" IsForeignKey="true" />
      <Association Name="Sys_FormMaster_fom_Sys_FormPurview_frp" Member="Sys_FormMaster_fom" ThisKey="frp_cFormNumber" OtherKey="fom_cFormNumber" Type="Sys_FormMaster_fom" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserSkin_urs" Member="UserSkin_urs">
    <Type Name="UserSkin_ur">
      <Column Name="urs_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="urs_cUserID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="urs_cSkinName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Sys_FormMaster_fom" Member="Sys_FormMaster_foms">
    <Type Name="Sys_FormMaster_fom">
      <Column Name="fom_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fom_iParentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fom_iIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fom_cFormNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="fom_cFormDesc" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fom_cExePath" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fom_cWebPath" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fom_cRemark" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="fom_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="fom_dAddDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="fom_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="fom_dLastDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="fom_iWebForm" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fom_iImageIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Sys_FormMaster_fom_Sys_FormPurview_frp" Member="Sys_FormPurview_frps" ThisKey="fom_cFormNumber" OtherKey="frp_cFormNumber" Type="Sys_FormPurview_frp" />
    </Type>
  </Table>
  <Table Name="dbo.LogDetail_lgd" Member="LogDetail_lgds">
    <Type Name="LogDetail_lgd">
      <Column Name="lgd_iID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lgd_cIpAddr" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="lgd_cSysName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="lgd_cClassMethodName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="lgd_cLogType" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="lgd_cLogMessage" Type="System.String" DbType="NVarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="lgd_cRemark" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="lgd_cOperator" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="lgd_dOperateDateTime" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DataRightsRole_ClassList_dtc" Member="DataRightsRole_ClassList_dtcs">
    <Type Name="DataRightsRole_ClassList_dtc">
      <Column Name="dtc_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dtc_cRoleNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="dtc_cDataRightType" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="dtc_iIsAllRights" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="dtc_cSchoolNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="dtc_cSpecialtyNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="dtc_cGraduationPeriod" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="dtc_cClassNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DataRightsRole_drr" Member="DataRightsRole_drrs">
    <Type Name="DataRightsRole_drr">
      <Column Name="drr_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="drr_cNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="drr_cName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="drr_cRemark" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="drr_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="drr_dAddDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="drr_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="drr_dLastDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DataRightsRole_TeacherList_dtl" Member="DataRightsRole_TeacherList_dtls">
    <Type Name="DataRightsRole_TeacherList_dtl">
      <Column Name="dtl_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dtl_cRoleNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="dtl_cDataRightType" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="dtl_iIsAllRights" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="dtl_cTeacherNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DataRightsRoleUser_dru" Member="DataRightsRoleUser_drus">
    <Type Name="DataRightsRoleUser_dru">
      <Column Name="dru_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dru_cRoleNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="dur_cUserLoginID" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CardUserMaster_cus" Member="CardUserMaster_cus">
    <Type Name="CardUserMaster_cus">
      <Column Name="cus_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cus_cNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cChaName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cEngName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cSexNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cIdentityNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cSchoolNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cDepartmentNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cSpecialtyNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cGraduationPeriod" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cClassNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cDormitorySiteNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cSMSReceivePhone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cus_lIsSendSMS" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="cus_lIsSendEmail" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="cus_lValid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="cus_cMailAddress" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cus_imgPhoto" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="cus_cRemark" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="cus_dAddDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="cus_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="cus_dLastDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="cus_guidPhotoKey" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="cus_cGroupNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cBedNum" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cPosition" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cAppendPhone1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cAppendPhone2" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cAppendPhone3" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cus_cGotoSchoolType" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cus_lCashPay" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="cus_cStudentId" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ArticleTypeDefine_atd" Member="ArticleTypeDefine_atds">
    <Type Name="ArticleTypeDefine_atd">
      <Column Name="atd_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="atd_cTypeNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="atd_cParentRecordNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="atd_cDescript" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="atd_lValid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="atd_cSysNum" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SchoolMaster_scm" Member="SchoolMaster_scm">
    <Type Name="SchoolMaster_scm">
      <Column Name="scm_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="scm_cNumber" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="scm_cName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="scm_cRemark" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="scm_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="scm_dAddDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="scm_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="scm_dLastDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SupplierMaster_slm" Member="SupplierMaster_slm">
    <Type Name="SupplierMaster_slm">
      <Column Name="slm_iRecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="slm_cClientNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="slm_cChinaName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="slm_cEnglishName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="slm_cTaxNumber" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="slm_cLinkman" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="slm_cAddress" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="slm_cPhone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="slm_cFax" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="slm_cWebSite" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="slm_cRemark" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="slm_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="slm_dAddDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="slm_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="slm_dLastDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VegetableSpeciesCycleTransaction_vsct" Member="VegetableSpeciesCycleTransaction_vsct">
    <Type Name="VegetableSpeciesCycleTransaction_vsct">
      <Column Name="vsct_RecordID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="vsct_VSTTRecordID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="vsct_cTransactionNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="vsct_lIsRemind" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="vsct_iAheadOfTimeRemind" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VegetableSpeciesMaster_vsm" Member="VegetableSpeciesMaster_vsm">
    <Type Name="VegetableSpeciesMaster_vsm">
      <Column Name="vsm_RecordID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="vsm_cNum" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="vsm_iSeq" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="vsm_cName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="vsm_cTypeNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="vsm_cByClassificationNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="vsm_iNurseryStage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vsm_iGrowingPeriod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vsm_iPickingPeriod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vsm_iAcreYield" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vsm_iPlastochron" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vsm_cRemark" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="vsm_cAdd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="vsm_dAddDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="vsm_cLast" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="vsm_dLastDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VegetableSpeciesMasterCost_vsmc" Member="VegetableSpeciesMasterCost_vsmc">
    <Type Name="VegetableSpeciesMasterCost_vsmc">
      <Column Name="vsmc_RecordID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="vsmc_VSMRevordID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="vsmc_cCostTypeNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="vsmc_cMTMNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="vsmc_fQty" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="vsmc_fUnitPrice" Type="System.Decimal" DbType="Decimal(18,4) NOT NULL" CanBeNull="false" />
      <Column Name="vsmc_cUnitNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VegetableSpeciesPerdictYield_vspy" Member="VegetableSpeciesPerdictYield_vspy">
    <Type Name="VegetableSpeciesPerdictYield_vspy">
      <Column Name="vspy_RecordID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="vspy_VSMRevordID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="vspy_iBeginDays" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vspy_iEndDays" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vspy_iYieldQty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vspy_cRemark" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VegetableSpeciesSuitPlantTime_vspt" Member="VegetableSpeciesSuitPlantTime_vspt">
    <Type Name="VegetableSpeciesSuitPlantTime_vspt">
      <Column Name="vspt_RecordID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="vspt_VSMRevordID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="vspt_iMonth" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VegetableSpeciesTransactionTime_vstt" Member="VegetableSpeciesTransactionTime_vstt">
    <Type Name="VegetableSpeciesTransactionTime_vstt">
      <Column Name="vstt_RecordID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="vstt_VSMRecordID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="vstt_cPlantingStatusNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="vstt_iCycleDatetime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vstt_cRemark" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VSCTransactionMaterial_vctm" Member="VSCTransactionMaterial_vctm">
    <Type Name="VSCTransactionMaterial_vctm">
      <Column Name="vctm_VSCTRecordID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="vctm_cMTMNum" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="vctm_fQty" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="vctm_cUnitNum" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>