//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceManage.SendMessagesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="sms", ConfigurationName="SendMessagesService.hsyzSoap")]
    public interface hsyzSoap {
        
        // CODEGEN: Generating message contract since element name uid from namespace sms is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="sms/SendSms", ReplyAction="*")]
        ServiceManage.SendMessagesService.SendSmsResponse SendSms(ServiceManage.SendMessagesService.SendSmsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="sms", Order=0)]
        public ServiceManage.SendMessagesService.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(ServiceManage.SendMessagesService.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="sms")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string uid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tophone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msg;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string uid, string pwd, string tophone, string msg) {
            this.uid = uid;
            this.pwd = pwd;
            this.tophone = tophone;
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="sms", Order=0)]
        public ServiceManage.SendMessagesService.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(ServiceManage.SendMessagesService.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="sms")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsResult;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(string SendSmsResult) {
            this.SendSmsResult = SendSmsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface hsyzSoapChannel : ServiceManage.SendMessagesService.hsyzSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class hsyzSoapClient : System.ServiceModel.ClientBase<ServiceManage.SendMessagesService.hsyzSoap>, ServiceManage.SendMessagesService.hsyzSoap {
        
        public hsyzSoapClient() {
        }
        
        public hsyzSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public hsyzSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public hsyzSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public hsyzSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceManage.SendMessagesService.SendSmsResponse ServiceManage.SendMessagesService.hsyzSoap.SendSms(ServiceManage.SendMessagesService.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public string SendSms(string uid, string pwd, string tophone, string msg) {
            ServiceManage.SendMessagesService.SendSmsRequest inValue = new ServiceManage.SendMessagesService.SendSmsRequest();
            inValue.Body = new ServiceManage.SendMessagesService.SendSmsRequestBody();
            inValue.Body.uid = uid;
            inValue.Body.pwd = pwd;
            inValue.Body.tophone = tophone;
            inValue.Body.msg = msg;
            ServiceManage.SendMessagesService.SendSmsResponse retVal = ((ServiceManage.SendMessagesService.hsyzSoap)(this)).SendSms(inValue);
            return retVal.Body.SendSmsResult;
        }
    }
}
