//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5456.
// 
#pragma warning disable 1591

namespace ServiceManage.SendDelayMessage {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsMsgSendingSoap", Namespace="http://tempuri.org/")]
    public partial class wsMsgSending : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendBatchSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBatchEmailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsMsgSending() {
            this.Url = global::ServiceManage.Properties.Settings.Default.ServiceManage_SendDelayMessage_wsMsgSending;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendBatchSmsCompletedEventHandler SendBatchSmsCompleted;
        
        /// <remarks/>
        public event SendBatchEmailCompletedEventHandler SendBatchEmailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendBatchSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendBatchSms(string[] listPhoneNum, string strContent, string strServName) {
            object[] results = this.Invoke("SendBatchSms", new object[] {
                        listPhoneNum,
                        strContent,
                        strServName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendBatchSmsAsync(string[] listPhoneNum, string strContent, string strServName) {
            this.SendBatchSmsAsync(listPhoneNum, strContent, strServName, null);
        }
        
        /// <remarks/>
        public void SendBatchSmsAsync(string[] listPhoneNum, string strContent, string strServName, object userState) {
            if ((this.SendBatchSmsOperationCompleted == null)) {
                this.SendBatchSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBatchSmsOperationCompleted);
            }
            this.InvokeAsync("SendBatchSms", new object[] {
                        listPhoneNum,
                        strContent,
                        strServName}, this.SendBatchSmsOperationCompleted, userState);
        }
        
        private void OnSendBatchSmsOperationCompleted(object arg) {
            if ((this.SendBatchSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBatchSmsCompleted(this, new SendBatchSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendBatchEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendBatchEmail(string[] listEmailAddr, string strTitle, string strContent, string strServName) {
            object[] results = this.Invoke("SendBatchEmail", new object[] {
                        listEmailAddr,
                        strTitle,
                        strContent,
                        strServName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendBatchEmailAsync(string[] listEmailAddr, string strTitle, string strContent, string strServName) {
            this.SendBatchEmailAsync(listEmailAddr, strTitle, strContent, strServName, null);
        }
        
        /// <remarks/>
        public void SendBatchEmailAsync(string[] listEmailAddr, string strTitle, string strContent, string strServName, object userState) {
            if ((this.SendBatchEmailOperationCompleted == null)) {
                this.SendBatchEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBatchEmailOperationCompleted);
            }
            this.InvokeAsync("SendBatchEmail", new object[] {
                        listEmailAddr,
                        strTitle,
                        strContent,
                        strServName}, this.SendBatchEmailOperationCompleted, userState);
        }
        
        private void OnSendBatchEmailOperationCompleted(object arg) {
            if ((this.SendBatchEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBatchEmailCompleted(this, new SendBatchEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendBatchSmsCompletedEventHandler(object sender, SendBatchSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBatchSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBatchSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SendBatchEmailCompletedEventHandler(object sender, SendBatchEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBatchEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBatchEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591